# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Meridian projection, cache, migration, and portability primitives.

This package composes registered Catalog Resources. It deliberately registers
no Catalog and starts no service, scheduler, broker, or Engine lifecycle.
"""

from meridian_storage.projection._version import __version__
from meridian_storage.projection.cache import (
    CACHE_ENVELOPE_FORMAT_VERSION,
    CacheBackend,
    CacheCoordinator,
    CacheOutcome,
    CachePolicy,
    CacheRead,
    CacheSerializer,
    CanonicalJsonSerializer,
    InMemoryCacheBackend,
    InvalidationResult,
    LoadedValue,
    MeridianCacheBackend,
    SourceVersionStrategy,
    VersionedCacheEntry,
)
from meridian_storage.projection.control import CancellationToken
from meridian_storage.projection.evidence import (
    EvidenceSink,
    InMemoryEvidenceSink,
    LifecycleEvidence,
    MeridianEvidenceSink,
    NullEvidenceSink,
)
from meridian_storage.projection.migration import (
    MIGRATION_FORMAT_VERSION,
    ActivationResult,
    AppliedMigrationStep,
    BindingStateEvidence,
    CompiledMigrationPlan,
    CompiledMigrationStep,
    CutoverEvidence,
    InMemoryMigrationRecorder,
    LockClass,
    MigrationAdapterHooks,
    MigrationBundleV1,
    MigrationCheckpoint,
    MigrationCondition,
    MigrationExecutor,
    MigrationLock,
    MigrationPlanner,
    MigrationRecorder,
    MigrationReport,
    MigrationState,
    MigrationStep,
    MigrationStepKind,
    MigrationValidationRunner,
    Reversibility,
    ValidationOutcome,
)
from meridian_storage.projection.outbox import (
    OUTBOX_FORMAT_VERSION,
    Checkpoint,
    InMemoryOutboxStore,
    OutboxDataV1,
    OutboxFailure,
    OutboxLease,
    OutboxPort,
    OutboxRecord,
    OutboxState,
    ProjectionLag,
    TransactionalOutboxWriter,
)
from meridian_storage.projection.portability import (
    LOGICAL_EXPORT_FORMAT_VERSION,
    ExportBoundary,
    ExportConsistency,
    ExportMetadata,
    ExportRequest,
    ImportReport,
    InMemoryLogicalArtifacts,
    LogicalArtifactSource,
    LogicalExportCoordinator,
    LogicalExportSink,
    LogicalExportSource,
    LogicalExportV1,
    LogicalImportCoordinator,
    LogicalImportTarget,
    LogicalRecord,
    MergePolicy,
    ObjectTransferHook,
    PartitionImportResult,
    PartitionManifest,
    PortableRecoveryCoordinator,
    RecoveryValidationHook,
    RestoreValidationEvidence,
)
from meridian_storage.projection.rebuild import (
    RebuildActivation,
    RebuildBoundary,
    RebuildCoordinator,
    RebuildEvidence,
    RebuildGeneration,
    RebuildHooks,
    RebuildPlan,
    RebuildTailResult,
    RebuildValidation,
)
from meridian_storage.projection.runner import (
    AcknowledgementExtractor,
    ProjectionContext,
    ProjectionRun,
    ProjectionRunner,
    ProjectionSpec,
    Projector,
    SourceVersionLoader,
)

__all__ = [
    "CACHE_ENVELOPE_FORMAT_VERSION",
    "LOGICAL_EXPORT_FORMAT_VERSION",
    "MIGRATION_FORMAT_VERSION",
    "OUTBOX_FORMAT_VERSION",
    "AcknowledgementExtractor",
    "ActivationResult",
    "AppliedMigrationStep",
    "BindingStateEvidence",
    "CacheBackend",
    "CacheCoordinator",
    "CacheOutcome",
    "CachePolicy",
    "CacheRead",
    "CacheSerializer",
    "CancellationToken",
    "CanonicalJsonSerializer",
    "Checkpoint",
    "CompiledMigrationPlan",
    "CompiledMigrationStep",
    "CutoverEvidence",
    "EvidenceSink",
    "ExportBoundary",
    "ExportConsistency",
    "ExportMetadata",
    "ExportRequest",
    "ImportReport",
    "InMemoryCacheBackend",
    "InMemoryEvidenceSink",
    "InMemoryLogicalArtifacts",
    "InMemoryMigrationRecorder",
    "InMemoryOutboxStore",
    "InvalidationResult",
    "LifecycleEvidence",
    "LoadedValue",
    "LockClass",
    "LogicalArtifactSource",
    "LogicalExportCoordinator",
    "LogicalExportSink",
    "LogicalExportSource",
    "LogicalExportV1",
    "LogicalImportCoordinator",
    "LogicalImportTarget",
    "LogicalRecord",
    "MergePolicy",
    "MeridianCacheBackend",
    "MeridianEvidenceSink",
    "MigrationAdapterHooks",
    "MigrationBundleV1",
    "MigrationCheckpoint",
    "MigrationCondition",
    "MigrationExecutor",
    "MigrationLock",
    "MigrationPlanner",
    "MigrationRecorder",
    "MigrationReport",
    "MigrationState",
    "MigrationStep",
    "MigrationStepKind",
    "MigrationValidationRunner",
    "NullEvidenceSink",
    "ObjectTransferHook",
    "OutboxDataV1",
    "OutboxFailure",
    "OutboxLease",
    "OutboxPort",
    "OutboxRecord",
    "OutboxState",
    "PartitionImportResult",
    "PartitionManifest",
    "PortableRecoveryCoordinator",
    "ProjectionContext",
    "ProjectionLag",
    "ProjectionRun",
    "ProjectionRunner",
    "ProjectionSpec",
    "Projector",
    "RebuildActivation",
    "RebuildBoundary",
    "RebuildCoordinator",
    "RebuildEvidence",
    "RebuildGeneration",
    "RebuildHooks",
    "RebuildPlan",
    "RebuildTailResult",
    "RebuildValidation",
    "RecoveryValidationHook",
    "RestoreValidationEvidence",
    "Reversibility",
    "SourceVersionLoader",
    "SourceVersionStrategy",
    "TransactionalOutboxWriter",
    "ValidationOutcome",
    "VersionedCacheEntry",
    "__version__",
]
